### ISSUE TITLE
axis labels and large numbers

### ISSUE THREAD

**Issue by fedeinthemix** [timbod7/haskell-chart#170]
With the following code snippet

```
import Graphics.Rendering.Chart.Easy
import Graphics.Rendering.Chart.Backend.Diagrams
...
main = do
  ...
  toFile fileOpts "tt_im3.eps" $ do
    plotParData mkIddbpl (fmap show [0.5,0.502.. 0.51]) ssd
    layout_x_axis . laxis_title .= "freq (Hz)"
    layout_x_axis . laxis_generate .= scaledAxis def (99e6,101e6)
    layout_y_axis . laxis_generate .= scaledAxis def (-200,-150)
```

the labels for the x-axis are rendered as "9.9e7 + 0.0", "9.9e7 + 1.0e6", ... (see attached picture).
This seems peculiar to me and would expect them as pure numbers, not as sums.

Am I doing something wrong? Is it possible to force them to appear as pure numbers?

Thanks for any advice.

[tt_im3.pdf](https://github.com/timbod7/haskell-chart/files/1254564/tt_im3.pdf)

**Comment by timbod7** [comment]
This behaviour is intentional.  See:

https://github.com/timbod7/haskell-chart/blob/master/chart/Graphics/Rendering/Chart/Axis/Floating.hs#L82

it's an oversight that the doc string wasn't exported, and hence didn't make it to hackage. The original PR is here:

https://github.com/timbod7/haskell-chart/pull/127

You can set your own rendering function with `la_labelf`:

```
data LinearAxisParams a = LinearAxisParams {
    -- | The function used to show the axes labels.
    _la_labelf  :: [a] -> [String],

    -- | The target number of labels to be shown.
    _la_nLabels :: Int,

    -- | The target number of ticks to be shown.
    _la_nTicks  :: Int
}
```

**Comment by fedeinthemix** [comment]
I see. Thank for the information!
