### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by ndmitchell** [timbod7/haskell-chart#171]
Chart-diagrams used to be in Stackage, which was nice, but it got shut out due to an optparse-applicative bound as part of https://github.com/fpco/stackage/issues/2569. Any chance of getting it back into Stackage?

CC @sid-kap who added it to Stackage originally

**Comment by tfausak** [comment]
`Chart` was on Stackage for a while (https://github.com/fpco/stackage/pull/3020), but it's currently failing with GHC 8.4.1 (#181).

**Comment by olynch** [comment]
It looks like Chart is compatible with ghc8.4 again as of https://github.com/timbod7/haskell-chart/commit/3f58acada37a6508b63f0453895c7c9a6916ffcb, could you move forward on removing the stackage constraint?

**Comment by timbod7** [comment]
I've not added Chart to stackage before - it's shown up there thanks to others. Can you tell me exactly what I need to do, or ideally, make the necessary stackage PR yourself?

**Comment by tfausak** [comment]
I have added `Chart` and friends to Stackage before, but I don't have the time to do so now. This PR is a good example of how to add something to Stackage: https://github.com/commercialhaskell/stackage/pull/3020. See also [the official documentation](https://github.com/commercialhaskell/stackage/blob/faec4aca7b6e082457f4be51117b5013755d196a/MAINTAINERS.md#adding-a-package) for more detailed instructions.

**Comment by olynch** [comment]
Would this mean that I would become that stackage maintainer for Chart and Chart-diagrams?

**Comment by tfausak** [comment]
More or less, yeah. You would be responsible for responding to bounds issues on Stackage. That often means opening an issue or PR here in response.

**Comment by olynch** [comment]
OK, sure, why not.

**Comment by barryfm** [comment]
I am not sure why chart-diagrams-1.9 does not build, but I have a Chart-gi-cairo and Chart-gi-gtk that do build for 8.6 with haskell-gi, but unfortunately they use a gi-cairo-render (https://github.com/cohomology/gi-cairo-render) which is not yet in hackage.  There seems to be lot of working code waiting for some decisions to be made about pushing code to hackage.

For the moment I am building my stuff for 8.6.3 with stackage 13.5 and nixos-unstable with my local
patched repositories.  I can make my Chart-gi-cairo and Chart-gi-gtk code avaiiable if you like, but it probably should be done as reorganization of the Chart directory layout, or my pushing out a Chart-gi-backends separate component myself.  It also requires the haskell-gi package deciding on a long term approach to their gi-cairo setup.  If anyone else is interested, i could publish my current chart-backends
repository to github, although I'm not sure how to treat it copyright-wise since it is mostly Tim Docker's code.

The hackage/stack approach does not seem to deal with interm code while the upstream packages sort themselves out.

**Comment by bravit** [comment]
`Chart-1.9.1` and `Chart-diagrams-1.9.2` are back to Stackage ([lts-13.18](https://www.stackage.org/lts-13.18)), so I close this issue.
