### ISSUE TITLE
Labels for log scale axis are not readable at all

### ISSUE THREAD

**Issue by Shimuuar** [timbod7/haskell-chart#214]
It's not the worst example but it's bad enough: 
![badlog](https://user-images.githubusercontent.com/100394/71765553-68ef2100-2f07-11ea-8c61-40e3b393cd47.png)

Counting nines is not pleasant and if we go above/below 10^±15 labels could easily eat half of the plot. And whole 1+9999 thing looks very strange

**Comment by clayrat** [comment]
Oh, so this is actually pretty old. The example at https://github.com/timbod7/haskell-chart/wiki/example-4 has proper labels, after that the function `showDs` was introduced in 2016 which switches to offsets when there are duplicate tick values. The question is however why do we get duplicate tick values - this also leads to having 1 minor tick per interval instead of 9.

**Comment by clayrat** [comment]
Turns out it's unrelated after all - the minor ticks are generated by a [heuristic](https://github.com/timbod7/haskell-chart/blob/master/chart/Graphics/Rendering/Chart/Axis/Floating.hs#L331-L337), and the label issue can be just solved by `nub`bing the outputs of `logTicks`.
