### ISSUE TITLE
Candle Margins On Axis Ends

### ISSUE THREAD

**Issue by jm4games** [timbod7/haskell-chart#89]
So I've been using a chart with candle plots and I can't seem to find a setting to margin the first and last candle plots so that they aren't being drawn off screen half way. Is there a setting for this (or a recommend work around)? If not I could probably try to implement a solution and create a pull request (unless someone else could do it real quick).  

If I did implement such a solution, would there be a desired approach in how I do it?

**Comment by timbod7** [comment]
I agree that the behaviour is unfortunate when the bars end on the chart boundaries. There's no setting specifically for this, though a few workarounds are possible. 

How would you like the output to be shown:
*  (A) extend the clip region somehow, so that the plot looks as is, but with the end candles projecting slightly into the axis area
* (B) extend the range of the plot just enough so that the candle fits in the plot area (in which case you will end up with axis labels not aligning with the ends of the axis)
* (C) extend the range of the plot to the next axis label (in which case there will be some extra space at either end of the plot).

The workaround for B is to explicitly specify the range of the axis. This will take some trial and error in determining the necessary range. The workaround for C is to add some extra (hidden) points to the chart using the `Graphics.Rendering.Chart.Plot.Hidden` type, to force the axis range to expand. A would require a code change, I think

**Comment by jm4games** [comment]
I think I will try going with C for now, and if that doesn't workout, look into A. Thanks a lot, I'll let you know what I go with and will close issue when I do.

**Comment by jm4games** [comment]
So the hidden plots seem to be working fine for me. Maybe I will attempt A at some point, but for now I will stick with C. Thanks!
